version: '3.8'

services:
  host:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_DASHBOARD_REMOTE: http://localhost:5001/assets/remoteEntry.js
        VITE_USER_REMOTE: http://localhost:5002/assets/remoteEntry.js
        VITE_REPORTS_REMOTE: http://localhost:5003/assets/remoteEntry.js
    ports:
      - '5000:5000'
    depends_on:
      - dashboard
      - user
      - reports
    networks:
      - mfe-network
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.remote
      args:
        APP_NAME: dashboard-app
        APP_PORT: 5001
    ports:
      - '5001:5001'
    networks:
      - mfe-network
    restart: unless-stopped

  user:
    build:
      context: .
      dockerfile: Dockerfile.remote
      args:
        APP_NAME: user-app
        APP_PORT: 5002
    ports:
      - '5002:5002'
    networks:
      - mfe-network
    restart: unless-stopped

  reports:
    build:
      context: .
      dockerfile: Dockerfile.remote
      args:
        APP_NAME: reports-app
        APP_PORT: 5003
    ports:
      - '5003:5003'
    networks:
      - mfe-network
    restart: unless-stopped

networks:
  mfe-network:
    driver: bridge
